name: Salisbury Framing
favicon: null
layout_spectrum: 0.8771645922679454
typography_spectrum: 0.3839303783606738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e11d2a'
    - '#ff0000'
    - '#bf0000'
    - '#800000'
    - '#000000'
  brandStrength: 0.7315308519173414
  lightness: 0.2013562098145485
  saturation: 0.563534565269947
  rhythmicContrast: 0.29983793245628476
purpose: []
