name: Salisbury Framing
favicon: null
layout_spectrum: 0.8771645922679454
typography_spectrum: 0.3839303783606738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9caeb8'
    - '#edfdfc'
    - '#442125'
    - '#cd8e0c'
    - '#b72442'
  brandStrength: 0.7315308519173414
  lightness: 0.2013562098145485
  saturation: 0.563534565269947
  rhythmicContrast: 0.29983793245628476
purpose: []
